# login:password -> guest:guest
version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      # This volume persists data so it is not lost when the container restarts
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: